app:
    build: .
    container_name: wb_api_app
    restart: always
    environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
        WB_API_KEY: ${WB_API_KEY}
        WB_API_TARIFFS: ${WB_API_TARIFFS}
        EXPRESS_PORT: ${EXPRESS_PORT}
        SERVICE_ACCOUNT_EMAIL: ${SERVICE_ACCOUNT_EMAIL}
        SERVICE_ACCOUNT_SCOPE: ${SERVICE_ACCOUNT_SCOPE}
        SERVICE_ACCOUNT_PRIVATE_KEY: ${SERVICE_ACCOUNT_PRIVATE_KEY}
        SPREADSHEET_IDS: ${SPREADSHEET_IDS}
    ports:
        - "${EXPRESS_PORT}:3000"
    depends_on:
        - db
